server:
  PORT: 4000

graphql:
  debug: true
  playground: true
  installSubscriptionHandlers: true

db:
  type: postgres
  host: localhost
  port: 5432
  username: docker
  password: docker
  database: rocketseat_challenge
  synchronize: true
  migrationsRun: false
  logging: false

kafka: &kafka
  transport: 6
  options: &kafka_options
    client:
      brokers:
        - localhost:9092
    consumer:
      groupId: submission-consumer\

kafka_services:
  submission:
    <<: *kafka
    name: KAFKA_SUBMISSION_SERVICE
